### PR TITLE
fix for #11

### PR DESCRIPTION
**Pull request by pablowbk**
Added title for base.html,
Fix Quotes off screen,
added padding for blogs preview,
added pointer cursors for btn

### CODE REVIEW

**Comment by pablowbk** [comment]
Will close this one and send new one with suggestions received in issue

**Comment by killbotXD** [comment]
@pablowbk why did you close the Issue? you can just push more commits on your master. They will be automatically reflected in this PR.

**Comment by pablowbk** [comment]
@killbotXD sorry, thought it would prevent conflicts. I can reopen it then, and commit the new fixes

**Comment by killbotXD** [comment]
I don't understand what conflicts you are talking about here. but yes reopen the PR and commit the fixes.

**Comment by pablowbk** [comment]
done!

**Comment by harsh-not-haarsh** [comment]
Hey @pablowbk , Can you also add some relevant screenshots here?

**Comment by pablowbk** [comment]
Sure thing.

- Changed hmtl title
image


- removed quotes shape
image


- added padding for blogs preview
image


- added pointer cursors for btn
image

**Review by harsh-not-haarsh — APPROVED** [review]

**Comment by pablowbk** [comment]
Could we add the #hacktoberfest label to this PR?

**Review by killbotXD — APPROVED** [review]
lgtm

**Comment by pablowbk** [comment]
Sorry to be this annoying... Seems the pr label needs to be "hacktoberfest-accepted"
If this is not much of a hassle to you, I'd appreciate it

Screenshot_20201020-124913~2

**Pull request merged**
